INSERT INTO `mydb`.`major_has_course` 
(`major_title`, `course_id`, `type`) 
VALUES 
("cs", (select id from course where subject="cs" and catalog_number=115), "major"),
("cs", (select id from course where subject="math" and catalog_number=161), "major"),
("cs", (select id from course where subject="cs" and catalog_number=215), "major"),
("cs", (select id from course where subject="cs" and catalog_number=210), "major"),
("cs", (select id from course where subject="cs" and catalog_number=242), "major"),
("cs", (select id from course where subject="cs" and catalog_number=252), "major"),
("cs", (select id from course where subject="cs" and catalog_number=315), "major"),
("cs", (select id from course where subject="cs" and catalog_number=355), "major"),
("cs", (select id from course where subject="cs" and catalog_number=370), "major"),
("cs", (select id from course where subject="cs" and catalog_number=351), "major"),
("cs", (select id from course where subject="cs" and catalog_number=415), "major"),
("cs", (select id from course where subject="cs" and catalog_number=454), "major"),
("cs", (select id from course where subject="cs" and catalog_number=470), "major"),
("cs", (select id from course where subject="cs" and catalog_number=460), "major"),
("cs", (select id from course where subject="cs" and catalog_number=450), "major"),

("cs", (select id from course where subject="cs" and catalog_number=340), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=330), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=349), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=360), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=365), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=375), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=385), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=390), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=452), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=465), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=480), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=495), "elective"),
("cs", (select id from course where subject="cs" and catalog_number=497), "elective"),

("cs", (select id from course where subject="math" and catalog_number=165), "support"),
("cs", (select id from course where subject="math" and catalog_number=211), "support"),
("cs", (select id from course where subject="math" and catalog_number=222), "support"),
("cs", (select id from course where subject="math" and catalog_number=241), "support"),
("cs", (select id from course where subject="math" and catalog_number=306), "support"),
("cs", (select id from course where subject="math" and catalog_number=316), "support"),
("cs", (select id from course where subject="math" and catalog_number=352), "support"),
("cs", (select id from course where subject="math" and catalog_number=416), "support"),
("cs", (select id from course where subject="math" and catalog_number=430), "support"),
("cs", (select id from course where subject="math" and catalog_number=470), "support"),
("cs", (select id from course where subject="phys" and catalog_number=214), "support");